/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by vite-plugin-auto-import-mdi-icons

import {
	mdiCog,
	mdiDotsVertical,
	mdiEyePlusOutline,
	mdiHome,
	mdiInformation,
	mdiPen,
	mdiWeatherNight,
	mdiWeatherSunny
} from "@mdi/js"

export default {
  mdiCog,
  mdiDotsVertical,
  mdiEyePlusOutline,
  mdiHome,
  mdiInformation,
  mdiPen,
  mdiWeatherNight,
  mdiWeatherSunny,
}
