/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBsbChart: typeof import('./src/components/VBsbChart.vue')['default']
    VBsbEditor: typeof import('./src/components/VBsbEditor.vue')['default']
    VBsbForm: typeof import('./src/components/VBsbForm.vue')['default']
    VBsbMap: typeof import('./src/components/VBsbMap.vue')['default']
    VBsbMedia: typeof import('./src/components/VBsbMedia.vue')['default']
    VBsbPad: typeof import('./src/components/VBsbPad.vue')['default']
    VBsbShare: typeof import('./src/components/VBsbShare.vue')['default']
    VBsbTable: typeof import('./src/components/VBsbTable.vue')['default']
    VBsbTableCell: typeof import('./src/components/VBsbTableCell.vue')['default']
  }
}
